project:
  type: website
  output-dir: docs
website:
  title: "R Geomatic"
  site-url: "https://rcarto.github.io/"
  favicon: "avatar.png"
  description: "Information on R spatial packages maintained by Timothée Giraud."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rCarto
      - text:  "{{< fa brands mastodon >}}"
        href: https://fosstodon.org/@rcarto
      - icon: rss
        href: index.xml
format:
  html:
    mainfont: "system-ui"
    monofont: "monospace"
    fontfamily: "system-ui"
    embed-resources: false
    self-contained-math: true
    html-math-method: plain
    
