project:
  type: website
  output-dir: docs
website:
  title: "R Geomatic"
  site-url: https://rcarto.github.io/
  description: "Information on R spatial packages maintained by @rcarto."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rCarto
      - text:  "{{< fa brands mastodon >}}"
        href: https://fosstodon.org/@rcarto
      - icon: rss
        href: index.xml
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css



